#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x9cceacf4, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x2dce5c0c, __VMLINUX_SYMBOL_STR(skb_queue_head) },
	{ 0x316ef669, __VMLINUX_SYMBOL_STR(release_sock) },
	{ 0xc28b8cde, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xd06990ae, __VMLINUX_SYMBOL_STR(sock_init_data) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x49c6fb25, __VMLINUX_SYMBOL_STR(tty_unlock) },
	{ 0x495ba03e, __VMLINUX_SYMBOL_STR(kernel_sendmsg) },
	{ 0x710dfb3f, __VMLINUX_SYMBOL_STR(single_open) },
	{ 0x15692c87, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0xcca27eeb, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x891d3927, __VMLINUX_SYMBOL_STR(dev_set_drvdata) },
	{ 0x4dda1cf6, __VMLINUX_SYMBOL_STR(single_release) },
	{ 0x4c86184b, __VMLINUX_SYMBOL_STR(remove_wait_queue) },
	{ 0xf946eda7, __VMLINUX_SYMBOL_STR(bt_sock_poll) },
	{ 0x11f21a1f, __VMLINUX_SYMBOL_STR(sock_release) },
	{ 0x7b6646bb, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xea2bd37f, __VMLINUX_SYMBOL_STR(hci_register_cb) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x7d2c0224, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0xafc6162c, __VMLINUX_SYMBOL_STR(bt_sock_ioctl) },
	{ 0x353e3fa5, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x74b5ede4, __VMLINUX_SYMBOL_STR(tty_register_driver) },
	{ 0x1976aa06, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0xfa2bcf10, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x1c2f2dfd, __VMLINUX_SYMBOL_STR(sock_create_kern) },
	{ 0xe1676390, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x61cf505f, __VMLINUX_SYMBOL_STR(put_tty_driver) },
	{ 0x44d41fbd, __VMLINUX_SYMBOL_STR(bt_sock_register) },
	{ 0x5d928850, __VMLINUX_SYMBOL_STR(kernel_listen) },
	{ 0xda68fb28, __VMLINUX_SYMBOL_STR(debugfs_create_file) },
	{ 0xadcbc910, __VMLINUX_SYMBOL_STR(hci_conn_check_secure) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x41f3df3b, __VMLINUX_SYMBOL_STR(seq_read) },
	{ 0x8323559e, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0xc44475bd, __VMLINUX_SYMBOL_STR(bt_sock_wait_state) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x45f3c4, __VMLINUX_SYMBOL_STR(tty_set_operations) },
	{ 0xb61a0c3b, __VMLINUX_SYMBOL_STR(bt_err) },
	{ 0x7c640527, __VMLINUX_SYMBOL_STR(bt_info) },
	{ 0xbbca194a, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xc0ff9eec, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xffd5a395, __VMLINUX_SYMBOL_STR(default_wake_function) },
	{ 0x54b260f7, __VMLINUX_SYMBOL_STR(bt_accept_enqueue) },
	{ 0xfb10409f, __VMLINUX_SYMBOL_STR(tty_port_put) },
	{ 0x32ec6731, __VMLINUX_SYMBOL_STR(bt_sock_unlink) },
	{ 0xe876827, __VMLINUX_SYMBOL_STR(bt_accept_unlink) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x6f0036d9, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0x8810359e, __VMLINUX_SYMBOL_STR(skb_queue_purge) },
	{ 0xd93389da, __VMLINUX_SYMBOL_STR(hci_get_route) },
	{ 0xf7f87f27, __VMLINUX_SYMBOL_STR(bt_accept_dequeue) },
	{ 0xbbd64246, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xf6190e38, __VMLINUX_SYMBOL_STR(kernel_connect) },
	{ 0x360adfc4, __VMLINUX_SYMBOL_STR(sk_alloc) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x57c61e1c, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0xaca13a27, __VMLINUX_SYMBOL_STR(lock_sock_nested) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x3b6776e3, __VMLINUX_SYMBOL_STR(tty_port_register_device) },
	{ 0x1a1a293e, __VMLINUX_SYMBOL_STR(hci_conn_security) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0xdfdb2b5e, __VMLINUX_SYMBOL_STR(debugfs_remove) },
	{ 0x2a12ec6c, __VMLINUX_SYMBOL_STR(tty_port_init) },
	{ 0x7bd60752, __VMLINUX_SYMBOL_STR(tty_insert_flip_string_fixed_flag) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x92281d58, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0xfb88016a, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x1ea06663, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x659b1b4e, __VMLINUX_SYMBOL_STR(device_move) },
	{ 0x83b90cfd, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0xc8fd727e, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x8fea24bd, __VMLINUX_SYMBOL_STR(bt_sock_unregister) },
	{ 0x9b705a29, __VMLINUX_SYMBOL_STR(tty_vhangup) },
	{ 0x6a7a7091, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0x1dcc8ab3, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0x2e2e2b0f, __VMLINUX_SYMBOL_STR(bt_sock_link) },
	{ 0xecec5d9a, __VMLINUX_SYMBOL_STR(device_create_file) },
	{ 0xddfdb360, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0x9ee13f47, __VMLINUX_SYMBOL_STR(skb_queue_tail) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0xfcf58fc5, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0xbb20732a, __VMLINUX_SYMBOL_STR(tty_unregister_device) },
	{ 0x6fef2591, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x67b27ec1, __VMLINUX_SYMBOL_STR(tty_std_termios) },
	{ 0xbc10dd97, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0xb0b27911, __VMLINUX_SYMBOL_STR(bt_debugfs) },
	{ 0x18c32f38, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0x36ead4ba, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x61c01090, __VMLINUX_SYMBOL_STR(bt_sock_stream_recvmsg) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x5691cf25, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x72ec83fc, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x122778d2, __VMLINUX_SYMBOL_STR(hci_unregister_cb) },
	{ 0x8688e1cc, __VMLINUX_SYMBOL_STR(bt_sock_reclassify_lock) },
	{ 0x67cf3ded, __VMLINUX_SYMBOL_STR(sock_alloc_send_skb) },
	{ 0x33e59e8f, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xd86bf91e, __VMLINUX_SYMBOL_STR(tty_unregister_driver) },
	{ 0x50a20d56, __VMLINUX_SYMBOL_STR(tty_hangup) },
	{ 0x2565cc3a, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0x21374251, __VMLINUX_SYMBOL_STR(kernel_accept) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x8bd0a3fd, __VMLINUX_SYMBOL_STR(_raw_write_unlock_bh) },
	{ 0x6652cb90, __VMLINUX_SYMBOL_STR(__tty_alloc_driver) },
	{ 0x409873e3, __VMLINUX_SYMBOL_STR(tty_termios_baud_rate) },
	{ 0xc7bcbc8d, __VMLINUX_SYMBOL_STR(add_wait_queue) },
	{ 0xeaf9bce, __VMLINUX_SYMBOL_STR(seq_lseek) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xc95a55a1, __VMLINUX_SYMBOL_STR(hci_conn_switch_role) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x9fb3dd30, __VMLINUX_SYMBOL_STR(memcpy_fromiovec) },
	{ 0xc5a3ed28, __VMLINUX_SYMBOL_STR(set_user_nice) },
	{ 0xa414882d, __VMLINUX_SYMBOL_STR(add_wait_queue_exclusive) },
	{ 0x7cd1912b, __VMLINUX_SYMBOL_STR(kernel_bind) },
	{ 0x85061b76, __VMLINUX_SYMBOL_STR(_raw_write_lock_bh) },
	{ 0x2d07ef2b, __VMLINUX_SYMBOL_STR(bt_procfs_init) },
	{ 0xc4a441f3, __VMLINUX_SYMBOL_STR(skb_dequeue) },
	{ 0x196031ad, __VMLINUX_SYMBOL_STR(tty_flip_buffer_push) },
	{ 0x95dbe078, __VMLINUX_SYMBOL_STR(__get_user_2) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0xf9ece494, __VMLINUX_SYMBOL_STR(tty_wakeup) },
	{ 0x6b77fa1b, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x6d044c26, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x4d56a0e4, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0x7af6a36d, __VMLINUX_SYMBOL_STR(bt_procfs_cleanup) },
	{ 0xb2858ae, __VMLINUX_SYMBOL_STR(tty_lock) },
	{ 0xf698c68c, __VMLINUX_SYMBOL_STR(try_module_get) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=bluetooth";


MODULE_INFO(srcversion, "CE230A40096C3D23342B3FC");
