#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xe8d22f15, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x5ee40dd6, __VMLINUX_SYMBOL_STR(vfs_create) },
	{ 0x12edb439, __VMLINUX_SYMBOL_STR(set_create_files_as) },
	{ 0x11960b55, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x79222a5, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x593f4298, __VMLINUX_SYMBOL_STR(set_security_override_from_ctx) },
	{ 0xa6cab0fd, __VMLINUX_SYMBOL_STR(security_path_rename) },
	{ 0x2e0047f, __VMLINUX_SYMBOL_STR(security_inode_mkdir) },
	{ 0xfbc74f64, __VMLINUX_SYMBOL_STR(__copy_from_user) },
	{ 0x22e1ae6f, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x67c2fa54, __VMLINUX_SYMBOL_STR(__copy_to_user) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xa0fbac79, __VMLINUX_SYMBOL_STR(wake_up_bit) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xe51c8f, __VMLINUX_SYMBOL_STR(prepare_kernel_cred) },
	{ 0x17d6e13, __VMLINUX_SYMBOL_STR(dget_parent) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xb5198b77, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x83668240, __VMLINUX_SYMBOL_STR(touch_atime) },
	{ 0xbdac1eb7, __VMLINUX_SYMBOL_STR(lockref_get) },
	{ 0xe4dfbb85, __VMLINUX_SYMBOL_STR(dput) },
	{ 0x2a3aa678, __VMLINUX_SYMBOL_STR(_test_and_clear_bit) },
	{ 0x2d50b651, __VMLINUX_SYMBOL_STR(dentry_open) },
	{ 0x2a3c98a0, __VMLINUX_SYMBOL_STR(add_to_page_cache_lru) },
	{ 0xa981d180, __VMLINUX_SYMBOL_STR(fscache_object_init) },
	{ 0x6f9a27f5, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xb2989ee, __VMLINUX_SYMBOL_STR(fscache_object_lookup_negative) },
	{ 0x87929f2b, __VMLINUX_SYMBOL_STR(path_get) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x41e77636, __VMLINUX_SYMBOL_STR(fscache_add_cache) },
	{ 0xe95f38f4, __VMLINUX_SYMBOL_STR(fscache_check_aux) },
	{ 0xc2936a0e, __VMLINUX_SYMBOL_STR(override_creds) },
	{ 0x8a210f93, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xdfafd384, __VMLINUX_SYMBOL_STR(security_inode_create) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x1ae4adb8, __VMLINUX_SYMBOL_STR(security_path_unlink) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x455293f6, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x189ad63e, __VMLINUX_SYMBOL_STR(unlock_rename) },
	{ 0x25631afd, __VMLINUX_SYMBOL_STR(fscache_cache_cleared_wq) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x48f68751, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0x31fb5227, __VMLINUX_SYMBOL_STR(misc_register) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x53c3121c, __VMLINUX_SYMBOL_STR(kern_path) },
	{ 0xa2173409, __VMLINUX_SYMBOL_STR(security_path_mkdir) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0xb840f323, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xc0f53c25, __VMLINUX_SYMBOL_STR(fscache_obtained_object) },
	{ 0x7646d580, __VMLINUX_SYMBOL_STR(kunmap) },
	{ 0x33dd3e34, __VMLINUX_SYMBOL_STR(vfs_getxattr) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x4d9b652b, __VMLINUX_SYMBOL_STR(rb_erase) },
	{ 0x8fc4ff01, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xa7f7b4ab, __VMLINUX_SYMBOL_STR(lock_rename) },
	{ 0x10da615, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0xd181e812, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xf3bc828e, __VMLINUX_SYMBOL_STR(fscache_withdraw_cache) },
	{ 0xdd27fa87, __VMLINUX_SYMBOL_STR(memchr) },
	{ 0x1c77112, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x82e5f1a3, __VMLINUX_SYMBOL_STR(fput) },
	{ 0xbbe8dd5d, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0xea0eb35e, __VMLINUX_SYMBOL_STR(fscache_mark_pages_cached) },
	{ 0x2fa26d84, __VMLINUX_SYMBOL_STR(fscache_mark_page_cached) },
	{ 0xe6b27c05, __VMLINUX_SYMBOL_STR(contig_page_data) },
	{ 0x3e6ca274, __VMLINUX_SYMBOL_STR(prepare_creds) },
	{ 0xa1f0ebea, __VMLINUX_SYMBOL_STR(bit_waitqueue) },
	{ 0x632780, __VMLINUX_SYMBOL_STR(work_busy) },
	{ 0xca9c707e, __VMLINUX_SYMBOL_STR(mntput) },
	{ 0x783b3563, __VMLINUX_SYMBOL_STR(wake_up_atomic_t) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x78f25a9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x4d0d163d, __VMLINUX_SYMBOL_STR(copy_page) },
	{ 0xc72c034a, __VMLINUX_SYMBOL_STR(kmap) },
	{ 0x1b1de11d, __VMLINUX_SYMBOL_STR(fscache_init_cache) },
	{ 0xdb7305a1, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x21a3fa86, __VMLINUX_SYMBOL_STR(fscache_object_destroy) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0xce5b480b, __VMLINUX_SYMBOL_STR(vfs_statfs) },
	{ 0x7b27c5dc, __VMLINUX_SYMBOL_STR(vfs_mkdir) },
	{ 0x8c36d23c, __VMLINUX_SYMBOL_STR(__put_cred) },
	{ 0x8a17ee98, __VMLINUX_SYMBOL_STR(path_put) },
	{ 0x8acd7080, __VMLINUX_SYMBOL_STR(vfs_truncate) },
	{ 0x47f03165, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x35d51a75, __VMLINUX_SYMBOL_STR(security_path_mknod) },
	{ 0x6f058086, __VMLINUX_SYMBOL_STR(fscache_put_operation) },
	{ 0xa5526619, __VMLINUX_SYMBOL_STR(rb_insert_color) },
	{ 0xe38228d2, __VMLINUX_SYMBOL_STR(vfs_unlink) },
	{ 0x565e4259, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x8d9ba8b, __VMLINUX_SYMBOL_STR(add_page_wait_queue) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x59502f01, __VMLINUX_SYMBOL_STR(__sb_end_write) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x721b1851, __VMLINUX_SYMBOL_STR(skip_spaces) },
	{ 0xba068adc, __VMLINUX_SYMBOL_STR(sync_filesystem) },
	{ 0x468337c2, __VMLINUX_SYMBOL_STR(fscache_io_error) },
	{ 0x91195dba, __VMLINUX_SYMBOL_STR(abort_creds) },
	{ 0xaba9d563, __VMLINUX_SYMBOL_STR(__sb_start_write) },
	{ 0x22406eb5, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x8f678b07, __VMLINUX_SYMBOL_STR(__stack_chk_guard) },
	{ 0x92cf98e, __VMLINUX_SYMBOL_STR(fscache_object_sleep_till_congested) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x7603bc97, __VMLINUX_SYMBOL_STR(find_get_page) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0xd5d0409, __VMLINUX_SYMBOL_STR(fscache_enqueue_operation) },
	{ 0x39d2f12c, __VMLINUX_SYMBOL_STR(lookup_one_len) },
	{ 0x1d1becad, __VMLINUX_SYMBOL_STR(vfs_rename) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x2227dbbd, __VMLINUX_SYMBOL_STR(fscache_op_complete) },
	{ 0x47c8baf4, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0xf5aaa177, __VMLINUX_SYMBOL_STR(notify_change) },
	{ 0xcc170397, __VMLINUX_SYMBOL_STR(vfs_setxattr) },
	{ 0xac0aef42, __VMLINUX_SYMBOL_STR(misc_deregister) },
	{ 0xf1b5e2e4, __VMLINUX_SYMBOL_STR(revert_creds) },
	{ 0xa069a88f, __VMLINUX_SYMBOL_STR(vfs_removexattr) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=fscache";

