#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xe8d22f15, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x33ba5cd4, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x5885fd5, __VMLINUX_SYMBOL_STR(bus_unregister) },
	{ 0xf89faed6, __VMLINUX_SYMBOL_STR(bus_register) },
	{ 0x565e4259, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x466b85b8, __VMLINUX_SYMBOL_STR(libceph_compatible) },
	{ 0x5d58b685, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x4205ffd7, __VMLINUX_SYMBOL_STR(ceph_destroy_options) },
	{ 0x48974e6c, __VMLINUX_SYMBOL_STR(device_register) },
	{ 0xe9b3a371, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0xbd920140, __VMLINUX_SYMBOL_STR(blk_queue_merge_bvec) },
	{ 0x609426c3, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0xf5453613, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0x759cdd13, __VMLINUX_SYMBOL_STR(blk_queue_max_segment_size) },
	{ 0x80f77476, __VMLINUX_SYMBOL_STR(blk_queue_max_hw_sectors) },
	{ 0x741c742d, __VMLINUX_SYMBOL_STR(blk_queue_physical_block_size) },
	{ 0xc42787a8, __VMLINUX_SYMBOL_STR(blk_init_queue) },
	{ 0xee18dea4, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0x5b72009f, __VMLINUX_SYMBOL_STR(ida_simple_get) },
	{ 0x7da08077, __VMLINUX_SYMBOL_STR(ceph_pg_poolid_by_name) },
	{ 0x6f9a27f5, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x5df47cab, __VMLINUX_SYMBOL_STR(ceph_open_session) },
	{ 0x6d216420, __VMLINUX_SYMBOL_STR(ceph_create_client) },
	{ 0x1f43f22a, __VMLINUX_SYMBOL_STR(ceph_compare_options) },
	{ 0x10da615, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xc55de604, __VMLINUX_SYMBOL_STR(ceph_parse_options) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x6c1ce5ce, __VMLINUX_SYMBOL_STR(strcspn) },
	{ 0xc7ec6c27, __VMLINUX_SYMBOL_STR(strspn) },
	{ 0xc17c6552, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0x3cb55f50, __VMLINUX_SYMBOL_STR(ceph_pg_pool_name_by_id) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x79b2ba90, __VMLINUX_SYMBOL_STR(blk_fetch_request) },
	{ 0x11ae80f9, __VMLINUX_SYMBOL_STR(__blk_end_request_all) },
	{ 0x2ab4ff5b, __VMLINUX_SYMBOL_STR(osd_req_op_raw_data_in_pages) },
	{ 0x4b8bbc1c, __VMLINUX_SYMBOL_STR(osd_req_op_init) },
	{ 0xfcd827d, __VMLINUX_SYMBOL_STR(bio_clone_bioset) },
	{ 0x50d15845, __VMLINUX_SYMBOL_STR(bio_advance) },
	{ 0x51546b3, __VMLINUX_SYMBOL_STR(fs_bio_set) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x573eabe6, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_bio) },
	{ 0xbc0ad9ac, __VMLINUX_SYMBOL_STR(osd_req_op_alloc_hint_init) },
	{ 0x170a247d, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pages) },
	{ 0x61ac8606, __VMLINUX_SYMBOL_STR(blk_end_request) },
	{ 0x73427209, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x83211609, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xa958ed4, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x1104f011, __VMLINUX_SYMBOL_STR(osd_req_op_cls_response_data_pages) },
	{ 0xd66b579e, __VMLINUX_SYMBOL_STR(osd_req_op_cls_request_data_pagelist) },
	{ 0x6ed41be2, __VMLINUX_SYMBOL_STR(ceph_pagelist_append) },
	{ 0x5e64cfbc, __VMLINUX_SYMBOL_STR(osd_req_op_cls_init) },
	{ 0xae3515ba, __VMLINUX_SYMBOL_STR(ceph_create_snap_context) },
	{ 0xd9ce8f0c, __VMLINUX_SYMBOL_STR(strnlen) },
	{ 0x7edd04a1, __VMLINUX_SYMBOL_STR(ceph_copy_from_page_vector) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xe4e893c6, __VMLINUX_SYMBOL_STR(osd_req_op_extent_osd_data_pages) },
	{ 0x5c516791, __VMLINUX_SYMBOL_STR(osd_req_op_extent_init) },
	{ 0xbc2181e4, __VMLINUX_SYMBOL_STR(ceph_alloc_page_vector) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x20df2681, __VMLINUX_SYMBOL_STR(ida_simple_remove) },
	{ 0xb7bc4b6b, __VMLINUX_SYMBOL_STR(blk_cleanup_queue) },
	{ 0x553448dc, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0x7f76dd5f, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0xa9a285d, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x271c2372, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xc4aa6175, __VMLINUX_SYMBOL_STR(device_unregister) },
	{ 0xe25b19d7, __VMLINUX_SYMBOL_STR(ceph_osdc_flush_notifies) },
	{ 0x996bdb64, __VMLINUX_SYMBOL_STR(_kstrtoul) },
	{ 0x777f8296, __VMLINUX_SYMBOL_STR(ceph_osdc_set_request_linger) },
	{ 0x7e54ab8a, __VMLINUX_SYMBOL_STR(ceph_osdc_create_event) },
	{ 0x4e74f66a, __VMLINUX_SYMBOL_STR(ceph_osdc_cancel_event) },
	{ 0x5613dbd7, __VMLINUX_SYMBOL_STR(osd_req_op_watch_init) },
	{ 0xc8fafc74, __VMLINUX_SYMBOL_STR(ceph_osdc_unregister_linger_request) },
	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
	{ 0x815f6e29, __VMLINUX_SYMBOL_STR(ceph_osdc_alloc_request) },
	{ 0xab694444, __VMLINUX_SYMBOL_STR(bsearch) },
	{ 0xc09f77f8, __VMLINUX_SYMBOL_STR(ceph_osdc_build_request) },
	{ 0xca54fee, __VMLINUX_SYMBOL_STR(_test_and_set_bit) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x54102470, __VMLINUX_SYMBOL_STR(ceph_client_id) },
	{ 0x5b15d300, __VMLINUX_SYMBOL_STR(set_device_ro) },
	{ 0x4e3e6b7a, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x3507a132, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x7d4e2276, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x3f688151, __VMLINUX_SYMBOL_STR(ceph_put_snap_context) },
	{ 0x54b2146c, __VMLINUX_SYMBOL_STR(ceph_destroy_client) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xfd5683b9, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible) },
	{ 0x6e644b25, __VMLINUX_SYMBOL_STR(ceph_osdc_start_request) },
	{ 0x81f3afb, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x48f68751, __VMLINUX_SYMBOL_STR(kmap_atomic) },
	{ 0xed93f29e, __VMLINUX_SYMBOL_STR(__kunmap_atomic) },
	{ 0x95bf15f4, __VMLINUX_SYMBOL_STR(flush_dcache_page) },
	{ 0xf2481c38, __VMLINUX_SYMBOL_STR(bio_put) },
	{ 0x8fc4ff01, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x9ae11ec8, __VMLINUX_SYMBOL_STR(ceph_release_page_vector) },
	{ 0x197effcb, __VMLINUX_SYMBOL_STR(ceph_osdc_release_request) },
	{ 0x22e1ae6f, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x6b2e3bcd, __VMLINUX_SYMBOL_STR(ceph_get_snap_context) },
	{ 0x455293f6, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x78f25a9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x47f03165, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x79222a5, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x11960b55, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=libceph";

