#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xe8d22f15, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf3017e21, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0xfcd02971, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0x64707a53, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x2c343a0a, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x67dab48d, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x12687d44, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0x495973e2, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0xe6dc15d5, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0xdbd80ad7, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xe464c4b8, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0x222d9b03, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x74129247, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x67fedfe2, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0x44b23ab, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0x91820180, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xb5c34ab5, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0xb17dd50c, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0xd78e6f89, __VMLINUX_SYMBOL_STR(security_skb_classify_flow) },
	{ 0xc0a36d9d, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0xbbb67b49, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0x1a826dc1, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0x6baa687c, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xb27fd897, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0x6bced8ec, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0xb81d3710, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xbb6579f7, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0xb2c1c509, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xc07b6b4, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0x4ce39368, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x3c5cf86, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xb6ecf069, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x4946abf7, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0xe14e84b8, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xec3274b4, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x665cfc11, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0xf8953791, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0xd7221942, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0xc9e817f6, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0x2deda4a1, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0xdb76797a, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xd14853e8, __VMLINUX_SYMBOL_STR(inet_csk_search_req) },
	{ 0xb4c5f507, __VMLINUX_SYMBOL_STR(inet_csk_delete_keepalive_timer) },
	{ 0x921e7e72, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0x8fc4ff01, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x24ea446, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0xd100acbd, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x1c773441, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x95ee0371, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0xbff781de, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0xcf020c0f, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0x2b1db369, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0x9a123b7, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0xab9c9212, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xa20ce1b8, __VMLINUX_SYMBOL_STR(net_msg_warn) },
	{ 0xccd90752, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0x6ce74a79, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0x5d06ac4, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0xf7ef6fc5, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0xd326790, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0xf8c29130, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x71fa5ace, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0xab51c64c, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x2a5908a5, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0x78f25a9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xfeaef677, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0x663a6ace, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0x9230ca5b, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0x8c0cd28f, __VMLINUX_SYMBOL_STR(__ip_route_output_key) },
	{ 0xe27e7a02, __VMLINUX_SYMBOL_STR(sk_release_kernel) },
	{ 0x7fc7bfa2, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xf1f859ea, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x109a330c, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x2b765735, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0xca872e04, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x44d498b7, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0x5f02756a, __VMLINUX_SYMBOL_STR(__inet_hash_nolisten) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x92647763, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0x2125f7d4, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0xbf75475a, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0x80c09f9d, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x80e54eb7, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x4fa7216e, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0xe850f4a0, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0xdd118a07, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xe1e37a91, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0x23692ea4, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x10381df0, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x5db88349, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0xfd85d10f, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x393a71dd, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0xc223845d, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x78cc1f2, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0x2b287fca, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x5919253f, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0xbfa6abb4, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0xe9ae18ce, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";

